config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
  }

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root to: 'cds#index'
  get '/thanks', to: 'thanks#thanks'

  # devise_for :users

  resources :cds, only: [:index, :show]
  resources :cd_names, only: [:index]
  resources :users, only: [:show, :edit, :update, :destroy]
  resources :carts, only: [:index, :create, :update, :destroy]
  resources :receipts, only: [:new, :create]
  resources :othersaddresses, only: [:new, :create, :update]
  resources :purchases, only: [:index]



  namespace :admins do
  		root to: 'admins#index'
  		resources :purchases, only: [:index]
		resources :receipts, only: [:update, :destroy]
		resources :users, only: [:index,:show, :edit, :update, :destroy]
		resources :artists, only: [:new, :index, :create, :destroy, :update, :edit]
		resources :cds do
		  resource :songs,only: [:create, :edit, :update, :destroy]
    end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  has_many :carts, dependent: :destroy
  has_many :othersaddresses, dependent: :destroy
  has_many :receipts

  acts_as_paranoid

  # adminsコントローラーからのデータ登録、更新の場合はバリデーションをスキップする
  # ======================================================
  def admins_namespace?
    @class_name.include?('Admins') if @class_name
  end

  def namespace(class_name)
    @class_name = class_name
  end
  # ======================================================

  with_options unless: :admins_namespace? do
    before_validation :set_postal_code
    before_validation :set_address
    before_validation :set_telephone_number

    validates :postal_code, format: { with: /\A\d{7}\z/ }
    validates :first_postal_code, :last_postal_code, presence: true
    validates :statu_address, :city_address, presence: true
    validates :telephone_number, format: { with: /\A\d{11}\z/ }
    validates :telephone_number1,
    :telephone_number2,
    :telephone_number3,
    presence: true
  end

  # 仮想カラムをセット
  attr_accessor :first_postal_code, :last_postal_code
  attr_accessor :statu_address, :city_address, :street_address
  attr_accessor :telephone_number1, :telephone_number2, :telephone_number3

  # データ仮想カラム用にを工して取り出すためのメソッド
  def first_postal_code
    @first_postal_code || self.postal_code[0..2] if self.postal_code.present?
  end

  def last_postal_code
    @last_postal_code || self.postal_code[3..6] if self.postal_code.present?
  end

  def statu_address
    @statu_address || self.split_address[:statu] if self.address.present?
  end

  def city_address
    @city_address || self.split_address[:city] if self.address.present?
  end

  def street_address
    @street_address || self.split_address[:street] if self.address.present?
  end

  def telephone_number1
    @telephone_number1 || self.telephone_number[0..2] if self.telephone_number.present?
  end

  def telephone_number2
    @telephone_number2 || self.telephone_number[3..6] if self.telephone_number.present?
  end

  def telephone_number3
    @telephone_number3 || self.telephone_number[7..10] if self.telephone_number.present?
  end

  # 仮想カラムを本来のカラムの状態に変換するメソッド
  def set_postal_code
    self.postal_code = [@first_postal_code, @last_postal_code].join
  end

  def set_telephone_number
    self.telephone_number = [@telephone_number1, @telephone_number2, @telephone_number3].join
  end

  def set_address
      self.address = [
        @statu_address.gsub(/[ |　]/,''),
        ' ',
        @city_address.gsub(/[ |　]/,''),
        '　',
        @street_address.gsub(/[ |　]/,'')
      ].join
  end

  # ============== address ==============
  # data保存時にstatu, city, streetの結合部に区切り文字を追加する。
  # 仮想データの取り出しを用意にするため

  def split_address
    address_pattern = /(?<statu>.*)[ ](?<city>.*)[　](?<street>.*)/
    return address_pattern.match(self.address)
  end

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < Admins::AdminsController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @receipts = Receipt.where(user_id: @user)
  end

  def edit
  end

  def update
      respond_to do |format|
        @user.namespace(self.class.to_s)
        if @user.update(user_params)
          format.html {
            redirect_to admins_user_path(@user),
            notice: 'User was successfully updated.'
          }
          # format.json {
          #   render :show, status: :ok, location: @user
          # }
        else
          format.html {
            redirect_to admins_user_path(@user),
            notice: @user.erorrs.full_messages
          }
          # format.json {
          #   render json: @user.errors, status: :unprocessable_entity
          # }
        end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admins_users_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(
        :familyname,
        :firstname,
        :kana_familyname,
        :kana_firstname,
        :postal_code,
        :address,
        :telephone_number,
        :email
      )
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:update, :show, :edit, :destroy]

  def show
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to user_path(current_user.id)
  	else
  		render :new
  	end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admins_users_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(
        :familyname,
        :firstname,
        :kana_familyname,
        :kana_firstname,
        :first_postal_code,
        :last_postal_code,
        :statu_address,
        :city_address,
        :street_address,
        :telephone_number1,
        :telephone_number2,
        :telephone_number3
        )
    end
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="body" style="margin-top: 50px;">
  <p class="notice"></p>

  <div class="container">

    <div class="col-md-10 offset-md-1 mt-5">
      <h4 class="mb-3">アカウント情報の変更
        <div class="float-right ml-4">
          <%= link_to '退会', @user, method: :delete,
          data: { confirm: '本当に削除しますか?' }, class: "btn btn-outline-danger" %>
        </div>
      </h4>

      <%= form_for @user, class: 'needs-validation' do |f| %>
      <div class="row">
        <div class="col-md-6 mb-3">
          <%= f.label :familyname, '姓' %>
          <%= f.text_field :familyname, class: "form-control"  %>
          <div class="invalid-feedback">
            Valid first name is required.
          </div>
        </div>

        <div class="col-md-6 mb-3">
          <%= f.label :firstname, '名' %>
          <%= f.text_field :firstname, class: "form-control" %>
          <div class="invalid-feedback">
            Valid last name is required.
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6 mb-3">
          <%= f.label :kana_familyname, 'セイ' %>
          <%= f.text_field :kana_familyname, class: "form-control" %>
          <div class="invalid-feedback">
            Valid first name is required.
          </div>
        </div>

        <div class="col-md-6 mb-3">
          <%= f.label :kana_firstname, 'メイ' %>
          <%= f.text_field :kana_firstname, class: "form-control" %>
          <div class="invalid-feedback">
            Valid last name is required.
          </div>
        </div>
      </div>

      <div class="row mb-3">
        <div class="col-md-2" >
          <%= f.label :first_postal_code, '郵便番号' %>
          <%= f.text_field :first_postal_code, class: "form-control" %>
          <div class="invalid-feedback">
            Please select a valid country.
          </div>
        </div>

        <div class="col-md-2 ">
          <%= f.label :last_postal_code %>
          <%= f.text_field :last_postal_code, class: "form-control" %>
          <div class="invalid-feedback">
            Please select a valid country.
          </div>
        </div>

      </div>

      <div class="row mb-3">

        <div class="col-md-2">
          <%= f.label :statu_address, '都道府県' %>
          <%= f.text_field :statu_address, class: "form-control" %>
          <div class="invalid-feedback">
            Please enter your shipping address.
          </div>
        </div>

        <div class="col-md-4">
          <%= f.label :city_address, '住所' %>
          <%= f.text_field :city_address, class: "form-control" %>
          <div class="invalid-feedback">
            Please enter your shipping address.
          </div>
        </div>

        <div class="col-md-6">
          <%= f.label :street_address, 'マンション名' %>
          <%= f.text_field :street_address, class: "form-control" %>
          <div class="invalid-feedback">
            Please enter your shipping address.
          </div>
        </div>
      </div>

      <div class="row mb-3">

        <div class="col-md-2">
          <%= f.label :telephone_number1, '電話番号' %>
          <%= f.telephone_field :telephone_number1, class: "form-control" %>
          <div class="invalid-feedback">
            Please enter a valid email address for shipping updates.
          </div>
        </div>

        <div class="col-md-2">
          <%= f.label :telephone_number2, '電話番号' %>
          <%= f.telephone_field :telephone_number2, class: "form-control" %>
          <div class="invalid-feedback">
            Please enter a valid email address for shipping updates.
          </div>
        </div>

        <div class="col-md-2">
          <%= f.label :telephone_number3, '電話番号' %>
          <%= f.telephone_field :telephone_number3, class: "form-control" %>
          <div class="invalid-feedback">
            Please enter a valid email address for shipping updates.
          </div>
        </div>

        <div class="col-md-6">
          <%= f.label :email, 'メールアドレス' %>
          <%= f.email_field :email, class: "form-control" %>
          <div class="invalid-feedback">
            Please enter a valid email address for shipping updates.
          </div>
        </div>

      </div>


      <div id="user-edit-button" class="text-center mt-5">
        <%= link_to "キャンセル", user_path(@user), class: "btn btn-danger", style:  "width: 120px;" %>
        <%= f.submit '更新', class: "btn btn-success", style: "width: 120px;" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="body" style="margin-top: 50px;">
	<div class="container">
    	<div class="row">
			<div class="col-md-8 offset-2">
			<table class="table table-bordered">
				<h4 class="">会員情報</h4>
				<tbody class="text-center">
					<tr>
						<th class="table-active">名前</th>
						<td ><%= @user.familyname %> <%= @user.firstname %></td>
					</tr>
					<tr>
						<th class="table-active">フリガナ</th>
						<td ><%= @user.kana_familyname %> <%= @user.kana_firstname %></td>
					</tr>
					<tr>
						<th class="table-active">郵便番号</th>
						<td ><%= @user.first_postal_code %> - <%= @user.last_postal_code %></td>
					</tr>
					<tr>
						<th class="table-active">住所</th>
						<td ><%= @user.address %></td>
					</tr>
					<tr>
						<th class="table-active">電話番号</th>
						<td ><%= @user.telephone_number1 %> - <%= @user.telephone_number2 %> - <%= @user.telephone_number3 %></td>
					</tr>
					<tr>
						<th class="table-active">メールアドレス</th>
						<td ><%= @user.email %></td>
					</tr>
				</tbody>
			</table>
				<div class="float-right">
					<span><%= link_to '編集', edit_user_path, :class => "btn btn-success"%></span>
					<span><%= link_to '購入履歴一覧', purchases_path(current_user.id), :class => "btn btn-primary" %></span>
				</div>
			</div>
		</div>
	</div>
</div>