config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
  }

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root to: 'cds#index'
  get '/thanks', to: 'thanks#thanks'

  # devise_for :users

  resources :cds, only: [:index, :show]
  resources :cd_names, only: [:index]
  resources :users, only: [:show, :edit, :update, :destroy]
  resources :carts, only: [:index, :create, :update, :destroy]
  resources :receipts, only: [:new, :create]
  resources :othersaddresses, only: [:new, :create, :update]
  resources :purchases, only: [:index]



  namespace :admins do
  		root to: 'admins#index'
  		resources :purchases, only: [:index]
		resources :receipts, only: [:update, :destroy]
		resources :users, only: [:index,:show, :edit, :update, :destroy]
		resources :artists, only: [:new, :index, :create, :destroy, :update, :edit]
		resources :cds do
		  resource :songs,only: [:create, :edit, :update, :destroy]
    end
	end
end

app/views/shared/_header.html.erb
    <nav class="navbar navbar-expand navbar-dark bg-dark fixed-top">
          <%= image_tag "logo.png", size: "270x100", alt: "metal-EC" %>

      <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "TOP", :root, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "カート", :carts, class: "nav-link" %>
        </li>
        <div class="dropdown">
          <button type="button" class="btn btn-secondary dropdown-toggle btn-md" id="dropdownMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_user.firstname %>さんログイン中</button>
          <div class="dropdown-menu btn-sm" aria-labelledby="dropdownMenu">
            <button class="dropdown-item" type="button"><%= link_to '会員情報', user_path(current_user.id), class: "nav-link text-body" %></button>
            <button class="dropdown-item" type="button"><%= link_to '購入履歴', purchases_path(current_user.id), class: "nav-link text-body" %></button>
          </div>
         </div>
         <li class="nav-item">
        <%= link_to 'ログアウト', :destroy_user_session, method: :delete, class: "nav-link" %>
      </li>
      <% else %>
      <li class="nav-item">
          <%= link_to "TOP", :root, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to 'ログイン', :new_user_session, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to '会員登録', :new_user_registration, class: "nav-link" %>
      </li>
      </ul>
         <% end %>
    </nav>