config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
  }

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root to: 'cds#index'
  get '/thanks', to: 'thanks#thanks'

  # devise_for :users

  resources :cds, only: [:index, :show]
  resources :cd_names, only: [:index]
  resources :users, only: [:show, :edit, :update, :destroy]
  resources :carts, only: [:index, :create, :update, :destroy]
  resources :receipts, only: [:new, :create]
  resources :othersaddresses, only: [:new, :create, :update]
  resources :purchases, only: [:index]



  namespace :admins do
  		root to: 'admins#index'
  		resources :purchases, only: [:index]
		resources :receipts, only: [:update, :destroy]
		resources :users, only: [:index,:show, :edit, :update, :destroy]
		resources :artists, only: [:new, :index, :create, :destroy, :update, :edit]
		resources :cds do
		  resource :songs,only: [:create, :edit, :update, :destroy]
    end
	end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :cd
  belongs_to :user


  validates :cd_id, presence: true
  validates :user_id, presence: true
  validates :amount, presence: true
end

app/controllers/carts_controller.rb
 class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:update, :destroy]

  #カート一覧表示
  def index
    @carts = current_user.carts
    @postage = 500
    @total_price = 0
  end

  #カートに商品を追加する
  def create
    cart = Cart.find_by(
      user_id: current_user.id,
      cd_id: cart_params[:cd_id]
    )

    if cart.present?
      # update
      # 既存のカートレコードに数量を追加
      cart.increment(:amount, cart_params[:amount].to_i)
    else
      # create
      # 新規でレコードを作成
      cart = Cart.new(
        user_id: current_user.id,
        cd_id: cart_params[:cd_id],
        amount: cart_params[:amount]
      )
    end

    cd = Cd.find(params[:cart][:cd_id].to_i)
    if cd.stock > 0
      cart.save
      flash[:notice] = "カートに商品が追加されました"
      redirect_to carts_path
    else
      flash[:notice] = "品切れのため商品を追加できません。"
      redirect_to cd
    end
  end

#カート商品の数量変更
  def update
    if params[:cart][:amount].to_i <= @cart.cd.stock
      @cart.update(cart_params)
      flash[:notice] = "購入数量を変更しました"
      redirect_to carts_path
    else
      flash[:notice] = "購入希望数の在庫がないため変更に失敗しました"
      redirect_to carts_path
    end
  end

 #カート商品の削除
  def destroy
    if @cart.destroy
    flash[:notice] = "削除しました"
    redirect_to carts_path
    else
    falsh[:notice] = "削除できませんでした"
    redirect_to cart_path
    end
  end

  private

  def set_user
      @cart = Cart.find(params[:id])
    end

  def cart_params
    params.require(:cart).permit(:cd_id, :user_id, :amount)
  end

end

app/helpers/carts_helper.rb
module CartsHelper


end

app/views/carts/index.html.erb
<div class="container">
  <% unless @carts.empty? %>
    <div class ="row">
      <h2  class="margin_top">ショッピングカート</h2>
      <div class="col-lg-12">
        <table class="table">
          <thead>
            <tr>
              <th width="150" style="border:none">商品画像</th>
              <th width="200" style="border:none">商品名</th>
              <th width="200" style="border:none">アーティスト名</th>
              <th style="border:none">価格(税込)</th>
              <th style="border:none">購入数量</th>
              <th style="border:none">小計</th>
              <th style="border:none"></th>
            </tr>
          </thead>
            <% @carts.each do |cart| %>
          <tbody>
            <tr>
              <td><%= attachment_image_tag cart.cd, :cd_image, size: "60x60", fallback: "no_image.jpg" %></td>
              <td><%= cart.cd.single_album_name %></td>
              <td><%= cart.cd.artist.artist_name %></td>
              <td><%= cart.cd.price %>円</td>
              <td><%= form_with model: cart, url: cart_path(cart) do |f| %>
                  <%= f.number_field :amount, min: 1, max: 99, step: 1 %>個
                  <%= f.submit "変更" %></td>
                  <% end %>
              <td><%= cart.cd.price * cart.amount %>円</td>
              <td><%= link_to "削除", cart_path(cart), class: "btn btn-outline-danger margin_top", method: :delete %></td>
            </tr>
          </tbody>
              <% @total_price += cart.cd.price * cart.amount %>
            <% end %>
        </table>
      </div>
    </div>


    <div class="clearfix">
    <table style="table-layout:fixed;width:30%;" class="table table-bordered text-right float-right">
      <colgroup>
        <col style="width:40%;">
        <col style="width:60%;">
      </colgroup>
      <tr>
        <th class="table-active">送料</th>
        <td><%= @postage %></td>
      </tr>
      <tr>
        <th class="table-active">合計(税込)</th>
        <td><%= @total_price + @postage %>円</td>
      </tr>
    </table>
    </div>

   <div class="text-right">
    <%= link_to "買い物を続ける", cds_path, class: "btn btn-outline-dark" %>
    <%= link_to "お支払いへ進む", new_receipt_path, class: "btn btn-primary" %>
   </div>
  <% else %>
    <h1 class="text-center">商品がカートに入っていません。</h1>
    <div class="text-center"><%= link_to "買い物をする", cds_path, class: "btn btn-outline-warning btn-lg mt-4" %></div>
  <% end %>
</div>