config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
  }

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root to: 'cds#index'
  get '/thanks', to: 'thanks#thanks'

  # devise_for :users

  resources :cds, only: [:index, :show]
  resources :cd_names, only: [:index]
  resources :users, only: [:show, :edit, :update, :destroy]
  resources :carts, only: [:index, :create, :update, :destroy]
  resources :receipts, only: [:new, :create]
  resources :othersaddresses, only: [:new, :create, :update]
  resources :purchases, only: [:index]



  namespace :admins do
  		root to: 'admins#index'
  		resources :purchases, only: [:index]
		resources :receipts, only: [:update, :destroy]
		resources :users, only: [:index,:show, :edit, :update, :destroy]
		resources :artists, only: [:new, :index, :create, :destroy, :update, :edit]
		resources :cds do
		  resource :songs,only: [:create, :edit, :update, :destroy]
    end
	end
end

app/models/artist.rb
class Artist < ApplicationRecord
	has_many :cds
	validates :artist_name, presence: true
end

app/controllers/admins/artists_controller.rb
class Admins::ArtistsController < Admins::AdminsController

	before_action :set_artist, only: [:destroy, :update]

	def new
		@artist = Artist.new
	end

	def create
		@artist = Artist.new(artist_params)
			respond_to do |format|
			if @artist.save
				format.html { redirect_to  new_admins_cd_path, notice: 'Artist was successfully created.' }
		    # format.json { render :show, status: :created, location: @artist }
			else
				@artists = Artist.all
				@cd = Cd.new
	      format.html { render "admins/cds/new" }
	      # format.json { render json: @user.errors, status: :unprocessable_entity }
	   	end
   end
	end

	def index
		@artists = Artist.all
	end

	def edit
	end

	def update
	  respond_to do |format|
	    if @artist.update (artist_params)
	      format.html { redirect_to new_admins_cd_path, notice: 'artist was successfully updated.' }
	      format.json { render "admins/cds/new", status: :ok, location: @artist }
	    else
	      format.html { render "admins/cds/new" }
	      # format.json { render json: @artist.errors, status: :unprocessable_entity }
	    end
	  end
	end


	def destroy
		@artist.destroy
		redirect_to new_admins_cd_path
	end

	private

		def set_artist
			@artist = Artist.find(params[:id])
		end

		def artist_params
			params.require(:artist).permit(:artist_name)
		end


end

app/helpers/admin/artists_helper.rb
module Admin::ArtistsHelper
end

app/views/admins/artists/_artist_modal.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalLong">
  アーティスト一覧を表示
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">アーティスト一覧</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">


        <div class="mb-8">
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th></th>
                  <th>アーティスト名</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <% @artists.each do |artist| %>
                  <td><%= artist.id %></td>
                  <td><%= artist.artist_name %></td>
                  <td><%= link_to 'Edit', new_admins_cd_path(id: artist.id) %></td>
                  <td><%= link_to "削除", admins_artist_path(artist),method: :delete %></td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        <div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
</div>
</div>

app/views/admins/artists/_new.html.erb
<%= form_for ([:admins, @artist]) do |f| %>
<%= render 'layouts/error_messages', model: f.object %>
  <div class="row">
  	<div class="col-sm-3">
  	 <%= f.label :artist_name, "【必須】アーティスト名" %>
  	</div>
  	<div class="col-sm-8">
  	 <%= f.text_field :artist_name, class: "form-control" %>
  	</div>
  	<div class="col-sm-1">
  	 <%= f.submit '登録', class:"btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/admins/artists/index.html.erb
<% @artists.each do |artist| %>
   <div class="table-responsive">
    <table class="table table-striped table-sm">
	    <thead>
  			<tr>
  				<th><%= artist.id %></th>
  				<th><%= artist.artist_name %></th>
  				<th><%= link_to "削除", admins_artist_path(artist),method: :delete %></th>
  			</tr>
		  </thead>
	 </table>
  </div>
<% end %>